name: Node.js Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  publish-gpr:
    #needs: build
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          #cache: 'yarn'
          registry-url: https://npm.pkg.github.com/
          scope: '@devzolo'
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false
      #- run: yarn test
      - run: pnpm run build
      - name: Delete Old Package
        uses: actions/delete-package-versions@v1
        with:
          package-name: 'node-native-gl'
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      # - name: Delete Old Release
      #   uses: dev-drprasad/delete-tag-and-release@v0.2.0
      #   with:
      #     delete_release: true
      #     tag_name: main
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Archive Release
      #   run: npm pack
      #   uses: thedoctor0/zip-release@master
      #   with:
      #     type: 'tar'
      #     path: './'
      #     filename: 'release.tar'
      #     exclusions: '*.git* /*node_modules/* /*build/* .editorconfig'
      # - name: Upload binaries to release
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: devzolo-node-native-gl-1.0.0.tgz
      #     asset_name: devzolo-node-native-gl-1.0.0.tgz
      #     tag: ${{ github.ref }}
      #     overwrite: true
      #     body: "This is @devzolo/node-native-gl"
